#--------------------------------------#
#           Eventials config           #
#--------------------------------------#
add-recipes: false
pre-command: true #Disabling kills lots of features/functionality
fancy-help: true
detailed-command-help: true
fancy-pl: true
command-aliases: true
use-hyperwarps: true
quick-warps: []
tell-death-coords: true
log-death-coords: true
enable-signtools: true
enable-weaponstats: true

discord-link: 'https://discord.gg/DMcxR5D'

enable-custom-bows: false
prevent-arrow-invulnerability: false

login-noteblock: true
show-recent-joins: true
max-recent-joins: 20
record-player-addresses: true

default-nophysics-radius: 32

# range (0-1], set to 1 (for 100%) to disable
skip-night-sleep-percent-required: 0.5
skip-storm-sleep-percent-required: 0.5
skip-thunder-sleep-percent-required: 0.5
count-gm3-in-sleep-required: false
count-gm1-in-sleep-required: false
only-skip-if-nighttime: true

inactive-days-until-player-delete: 200
#Advancements checker is broken
keep-if-has-x-advancements: 100
keep-if-time-played-outweighs-time-inactive: true
keep-if-above-starting-balance: true
keep-if-whitelisted: true
keep-if-op: true

#A list of global cooldowns between when players can run commands
#Time is in seconds. Can by bypassed with 'eventials.bypass.waitcommands'
#To bypass a specific command, use 'eventials.bypass.waitcommands.cmd'
global-command-cooldowns:
  weather: 1200

#--------------------------------------#
#           EvEconomy config           #
#--------------------------------------#
economy-enabled: false

#Set track-server-balance to false for an infinite server balance
track-server-balance: true
starting-server-balance: 10000
track-global-balance: true
starting-global-balance: 10000
starting-balance: 0
server-pays-starting-balance: true
custom-baltop: true

#A list of commands with prices attached to them
#Not guaranteed to work with all plugins!
#Use 'eventials.bypass.paidcommands' to bypass all commands or
#'eventials.bypass.paidcommands.cmd' for a specific commands
paid-commands:
  weather: 20.0

update-balance-watch: false
update-balance-on-paid-commands: true
update-balance-commands:
  - pay
  - withdraw
  - deposit
  - sell
  - moneyorder
  - bal
  - balance
  - eco
  - economy
  - serverbal

use-item-as-currency: true
currency-item: LILY_PAD
currency-symbol: '&2L'

ad-cost: 100
ad-default: '&7Your advertisement here, for only 100L'
ad-max-length: 43
#Duration in days
ad-duration: 14
#The date in milliseconds of the current ad's expiration
ad-expires-on: 0

#Currently, there are 55 vanilla advancements
advancement-reward: true
advancement-completion-prize: 500
advancement-exponential-base: 1.05
advancement-constant-multiplier: 10
advancement-min-before-reward: 5
advancement-max-reward: 500
advancements-included:
  - story
  - adventure
  - nether
  - end
  - husbandry

login-daily-money: 5
online-when-daily-money-bonus: 1
announce-daily-money: true
economy-signs: true

enable-moneyorders: false
moneyorder-min: 10
moneyorder-max: 1000
moneyorder-tax-percent: 25

#Adjust chunk generation cost per-world
default-chunk-generate-cost: 0
chunk-generate-cost:
  MysteryPeaks: 0.1
  MysteryPeaks_nether: 0.07
  MysteryPeaks_the_end: 0.05
# What happens when a player can't afford the chunk-generate-cost
# Possible values are: TP_SPAWN, NOTHING
chunk-generate-failure: TP_SPAWN

#--------------------------------------#
#           Messenger config           #
#--------------------------------------#
#Frequency of the clock in seconds
scheduler-enabled: true
clock-period: 60 #Default 60s per cycle

#To disable a task, set its frequency to 0
cycles-per-eventials-data-save: 2
cycles-per-automessage: 5
cycles-per-mob-clear: 0
cycles-per-worldsave: 5
cycles-per-player-delete: 1440
cycles-per-magic-day-reward: 60
cycles-per-holiday-action: 5

skip-automessage-if-other-event: true
skip-automessage-if-no-chats: true

#Remember usernames for personalized automsgs
save-ips: true
max-saved-ips: 200

message-color: '&e'
message-prefix: '&3[&7HC&3]&e '
#Auto-messages were moved to bottom of the file
#(because there are a lot of them)

custom-ping: true
ping-prefix: '&9&l&m  &7 ' # '  &9&l&m -&7 '
#Ping messages are at the bottom of this file

blacklisted-ips:
  - ''

prevent-multicraft-list-console-spam: false

#--------------------------------------#
#           EvSpawner config           #
#--------------------------------------#
evspawner-enabled: true
require-silktouch: true
stackable-spawners: true
drop-monsteregg-blocks: true
allow-nbt-container-placement: true
allow-nbt-commandblock-placement: true
allow-colorcodes-in-commandblock: true

#These do not require 'evspawner-enabled: true'
disable-skeleton-traps: false
allow-mob-armies: false
army-size-mean: 100
army-size-standard-deviation: 100
army-spawn-likelyhood: .002
army-enable-recursive-spawning: true
feed-slimes: true

#--------------------------------------#
#            EvVoter config            #
#--------------------------------------#
evvoter-enabled: true

#To disable voting streaks, set 'op' and 'amount' to 0
#op 0=add, 1=multiply, 2=
vote-streak-op: 0
vote-streak-amount: 0
vote-streak-max-days: 10
#How much time before a vote streak is lost?
vote-streak-grace-hours: 48

player-cash-reward: 0
server-cash-reward: 0
server-pays-player-cash-reward: true

vote-site-page: 'http://www.altcraft.net/voting'
vote-links:
  - 'PMC, https://www.planetminecraft.com/server/alternatecraft-2724346/vote/'
  - 'MMP, http://minecraft-mp.com/server/109051/vote/'
  - 'MC Servers, http://minecraftservers.org/vote/280048'
  - 'MCSL, http://minecraft-server-list.com/server/254265/vote/'
  - 'MC biz, https://minecraftservers.biz/servers/2600/vote/'
# - 'MC Index, https://www.minecraft-index.com/31471-alternatecraft/vote'

#--------------------------------------#
#          BookEditor config           #
#--------------------------------------#
book-editor-enabled: true

#--------------------------------------#
#             Split Worlds             #
#--------------------------------------#
splitworlds-enabled: true
vaccinate-players: true

# Groups of worlds that share the inventories. World inventories are separate by default
# Groups can be named whatever you like, but be precise with world names. * is wild.
# WARNING: Decide how to group worlds before they are opened; when two or more worlds are
# joined, only one of them will retain it's playerdata information
shared-inv-worlds:
  default_group:
    - '*'
    - '*_nether'
    - '*_the_end'

#--------------------------------------#
#              More Stuff              #
#--------------------------------------#
world-borders:

#Legend: &e = text, &b = link/download, &d = @Location, &2 = command, &a = $money/event/world, 
#Legend: &9 = suggest_command, &n = other location, &c = plugin, &6 = rss pack, &r = end special block
auto-messages:
  - |
       Hardcore is still in &bBETA&r.
       There may still be adjustments to mechanics
  - |
       We have an ongoing stats challenge!
       Top players (on Aug 25th) will receive a &aprize=>&7Choice of 20USD or a unique in-game reward!&r!
  - |
       As part of &bBETA&r, be prepared for tweaks, fixes,
       and possibly even map restarts during this time.
  - 'Teaming is encouraged, but always be cautious!'
  - 'Remember, anyone can join- be careful around others!'
  - |
       For the opening of Hardcore, we're hosting an Event!
       Top players in each of 3 objectives win a prize!
  - 'Beware public locations such as x=0,z=0 and The End!'
  - 'Feeling plain? Try &2/color&r!'
  - |
       The statistics that determine the prize-winners
       are shown in TAB, sidebar, and under player names
  - |
       The 3 stats for which you can win prizes are:
       (&71&r) Number of &bAdvancements=>https://minecraft.gamepedia.com/Tutorials/Advancement_guide&r, (&72&r) XP Levels,
       and (&73&r) # of Player Kills :o
  - 'Death-trapping End portals is bannable'
  - 'You get ONE /tpa, /tpahere, and /tpaccept. Use wisely!'
  - |
       Periodically, custom server &aEvents=>&7What got AlternateCraft started!&r will be held!
       Check out &baltcraft.net=>http://www.altcraft.net/events/&r, or wait and be surprised!
  - '&4[&c&lWarning&4]&r Unused terrain may be periodically reset!'
  - 'Griefing is generally discouraged'
  - |
       Exploring generates new chunks.
       When Minecraft updates, new terrain and features
       &owill not be present&r in those chunks!
  - |
       Sick of survival?
       Try out the &aCreative&r world!
  - 'Curious about your horse? Check out &2/hm'
  - 'Ye like? Ye support? &2/vote&r for links!'
  - 'Funding help isn''t required, but is always appreciated :)'
  - 'Wanna see a half-baked website? Visit &baltcraft.net=>http://www.altcraft.net'
  - 'Suggestions always welcome!'
  - 'Please check &2/rules&r periodically for updates'
  - 'Sharing server IPs is fine, but &nno soliciting&r please'
  - 'Staff are here to help, so ask away!'
  - 'Slaughter is fun, so why not start a head collection? ;)'
#  - 'Want to compete? Drop off your stuff and head to &2/arenas&r!'
#  - |
#       Win the &nMarket Parkour&r for a stack of diamond blocks!
#       (Warning, it is practically impossible)
#  - 'Unwarranted griefing can result in jail -> tempban'
#  - |
#       We recommend the &6LithosCore&r texture pack-
#       You can download the customized version &bhere=>http://www.altcraft.net/LithosCoreSimplified.zip&r.
  - 'YouTuber? Promote your channel, ask for the prefix!'
  - 'Found a bug? &2/mail Admin&r so we can fix it!'
#  - 'See a &2/green&r command? Click it to run it!'
#  - |
#       Many commands have aliases!
#       Examples: &2/home&r&7 -> &2/h&r, &2/back&r&7 -> &2/b&r, &2/f power&r&7 -> &2/f p
#  - |
#      Some ugly base in your way that needs to be taken down?
#      Please ask a staff member to get the thumbs up!
  - '(disabled) Want to see an epic world map? Visit Dynmap!'
  - 'Event schedule (irregularly) posted on our &bwebsite=>http://www.altcraft.net/events/schedule'
#  - |
#       Have something important to tell? Looking for ways
#       to promote your &d@Marketplace&r shop? Try &2/advertise&r!
  - '@ Server admins: Avoid &cClearLagg&r, it sucks!'
  - |
       We believe in server transparency!
       Check out &2/pl&r or the &bplugins page=>http://www.altcraft.net/plugins&r of the website
       Remember, suggestions are always welcome!
  - 'I used to be indecisive. Now I''m not sure...'
  - '&c&lPro Tip:&r&o don''t eat the yellow snow'
  - 'Check out other worlds and gamemodes with &2/server'

ping-messages:
  - ''
  - 'Wazzup %name%?'
  - 'Event ongoing, prizes to be awarded August 30th!'
  - 'Omae Wa Mou Shindeiru'
  - 'Event ongoing til August 25th'
  - ''
  - 'Press &fRefresh&r for more random ping messages!'
  - 'Yeet a bug'
  - 'Win up to $60 cash by August 25th!'
  - ''
  - 'Chicken Fried Steak'
  - 'A Minecraft Server'
  - 'Challenge 1/3: Most experience levels'
  - ''
  - '&oFreebuild creative!'
  - '&oCustom, Flat, and Vanilla worlds!'
  - 'Challenge 2/3: Most advancements completed'
  - ''
  - 'Hey %name%, wanna drop by today? :D'
  - '&oMarketplace!'
  - 'Challenge 3/3: Most players killed! :o'
  - ''
  - '&oPlots world coming "soon"!'
  - 'Now with additional lag!'
  - 'Dying also resets your progress towards challenges!'
  - ''
  - '&oPeriodic Events!'
  - 'Suggestions welcome!'
  - 'Goal 3/3 may get replaced, final decision by Aug 1'
  - ''
  - 'Press [refresh] for more random messages!'
  - '&ohard'
  - Yawn
  - 'Teaming is encouraged!'
  - ''
  - 'The mind is weak but the body is strong.'
  - 'Live by the sword and die by the sword!'
  - ''
  - 'Tries to be unique'
  - 'OMAE WA MOU SHINDEIRU'
  - '&oYOLO'