#--------------------------------------#
#           Eventials config           #
#--------------------------------------#
server-name: Leafcraft

add-recipes: false

pre-command: tru
fancy-pl: true
command-aliases: true
show-permissionless-commands-in-plugin-help: true
use-hyperwarps: true
quick-warps: [adminshop, market]
tell-death-coords: false
log-death-coords: true
enable-signtools: true
enable-weaponstats: true

discord-link: 'https://discord.gg/DMcxR5D'

enable-custom-bows: false
prevent-arrow-invulnerability: false
shift-click-to-ride-in-gm1: true

click-to-remove-eyes-of-ender: true
remove-eye-of-ender-shatter-chance: 0.2
add-extra-strongholds: true

# Do not set this lower than 24320
extra-stronghold-min-distance-to-origin: 25856

# This will space strongholds roughly ~4050 blocks apart
extra-stronghold-density-in-km2: 0.06094490701
extra-stronghold-max-random-offset: 6076

login-noteblock: true
login-show-recent-joins: false
max-recent-joins-shown: 0
max-recent-joins-stored: 50
record-player-addresses: true

default-nophysics-radius: 32

inactive-days-until-player-delete: 999
keep-if-has-x-advancements: 20
keep-if-time-played-outweighs-time-inactive: true
keep-if-above-starting-balance: true
keep-if-whitelisted: true
keep-if-op: true

#A list of global cooldowns between when players can run commands
#Time is in seconds. Can by bypassed with 'eventials.bypass.waitcommands'
#To bypass a specific command, use 'eventials.bypass.waitcommands.cmd'
global-command-cooldowns:
  weather: 1200

fix-paper-rng-manip: true
fix-paper-gravity-dupe: true

#--------------------------------------#
#           EvEconomy config           #
#--------------------------------------#
economy-enabled: false

#--------------------------------------#
#           Messenger config           #
#--------------------------------------#
scheduler-enabled: false

#--------------------------------------#
#           EvSpawner config           #
#--------------------------------------#
evspawner-enabled: false
require-silktouch: true
stackable-spawners: false
drop-monsteregg-blocks: false
allow-nbt-container-placement: true
allow-nbt-commandblock-placement: true
allow-colorcodes-in-commandblock: true

#These do not require 'evspawner-enabled: true'
disable-skeleton-traps: false
allow-mob-armies: false
army-size-mean: 100
army-size-standard-deviation: 100
army-spawn-likelyhood: .002
army-enable-recursive-spawning: true
feed-slimes: false
dye-shulkers: true

#--------------------------------------#
#            EvVoter config            #
#--------------------------------------#
evvoter-enabled: true
player-cash-reward: 0

# Voting streaks can be used to modify the player-cash-reward amount.
# To disable voting streaks, set 'op' and 'amount' to 0.
vote-streak-op: 0 #op 0=add, 1=multiply, 2=tbd
vote-streak-amount: 0
vote-streak-max-days: 10
vote-streak-grace-hours: 48

vote-site-page: ''
vote-links:
  - 'MMP, http://minecraft-mp.com/server/320576/vote/'
  - 'MCS, https://minecraftservers.org/vote/651717'
  - 'PMC, https://www.planetminecraft.com/server/hardcore-4368271/vote/'

# Available params: %uuid%, %name%, %display_name%, %site_name%, %site_url%, %votes%, %streak%
vote-triggered-commands:
  - 'minecraft:scoreboard players add %name% pstats-votes 1'
  - 'minecraft:tellraw @p[name=!%name%] ["",{"text":"[","color":"gold"},{"text":"Leaf","color":"green"},{"text":"]","color":"gold"},{"text":" %display_name% up-voted the server on ","color":"gray"},{"text":"%site_name%","clickEvent":{"action":"open_url","value":"%site_url%"}}]'
  - 'minecraft:tellraw @p[name=%name%] ["",{"text":"[","color":"gold"},{"text":"Leaf","color":"green"},{"text":" ->","color":"gold"},{"text":" Me","color":"aqua"},{"text":"]","color":"gold"},{"text":" Thanks for voting for us on ","color":"gray"},"%site_name%",{"text":"!","color":"gray"}]'

# Available params: %uuid%, %name%, %display_name%, %votes%, %streak%, %reward_amount%, %reward_amount_int%
vote-triggered-commands-once-online:
  - 'minecraft:give %name% lily_pad{display:{Name:''{"text":"Vote Token","color":"#008800","italic":false}'',Lore:[''{"text":"Unplacing","color":"gray","italic":false}'',''{"text":"Soul Bound","color":"gray","italic":false}'']},Enchantments:[{id:lure,lvl:1}],HideFlags:1,CustomModelData:1}'
#  - 'minecraft:tellraw @p[name=%name%] {"text":"Your offline votes were added, thanks!","color":"gray"}'

#--------------------------------------#
#          BookEditor config           #
#--------------------------------------#
book-editor-enabled: false

#--------------------------------------#
#             Split Worlds             #
#--------------------------------------#
splitworlds-enabled: true

shared-inv-worlds:
  default_group:
    - '*'
    - '*_nether'
    - '*_the_end'

#--------------------------------------#
#             Mail Service             #
#--------------------------------------#
mailbox-enabled: false
bridge-host: 'altcraft.net'
bridge-port: 42374
mailbox-max-connections: 100

# Prices for sending/receiving different items are set in 'mail_fees.csv'.
# Items with no specified price can only be mailed if 'default-price' is >=0.
# Alternatively, items with the 'mailable' tag can be mailed for free.

default-sending-fee: -1 #-1 to disable sending
default-receiving-fee: -1 #-1 to disable receiving
container-fee-includes-contents: true

#--------------------------------------#
#              More Stuff              #
#--------------------------------------#
world-borders:
  DaWorld:
    center-x: 0.5
    center-z: 0.5
    radius: 300000
  DaWorld_nether:
    center-x: 0.5
    center-z: 0.5
    radius: 37500
  DaWorld_the_end:
    center-x: 0.5
    center-z: 0.5
    radius: 37500

ping-messages:
  - ''